export const GET_ASIGNATURA = "GET_ASIGNATURA"
export const GET_ASIGNATURA_OK = "GET_ASIGNATURA_OK"
export const GET_ASIGNATURA_FAIL = "GET_ASIGNATURA_FAIL"

export const DELETE_ASIGNATURA = "DELETE_ASIGNATURA"
export const DELETE_ASIGNATURA_OK = "DELETE_ASIGNATURA_OK"
export const DELETE_ASIGNATURA_FAIL = "DELETE_ASIGNATURA_FAIL"