export const GET_ALUMNOS = "GET_ALUMNOS"
export const GET_ALUMNOS_OK = "GET_ALUMNOS_OK"
export const GET_ALUMNOS_FAIL = "GET_ALUMNOS_FAIL"

export const DELETE_ALUMNO = "DELETE_ALUMNO"
export const DELETE_ALUMNO_OK = "DELETE_ALUMNO_OK"
export const DELETE_ALUMNO_FAIL = "DELETE_ALUMNO_FAIL"